export const shopMenuArr = [
  "Appliances",
  "Tools",
  "Clothing",
  "Shoes",
  "Lawns & Garden",
  "Outdoor Living & Patio",
  "Home",
  "Fitness & Sports",
  "TVs & Electronics",
  "Mattresses & Accessories",
  "Toys & Games",
  "Jewelry & watches",
  "Seasonal",
  "Parts & Accessories",
  "Fan Shop",
  "Automotive",
  "Baby",
  "Beauty",
  "Books & Magazines",
  "Connectes Solutions",
  "Food & Grocery",
  "Health & Wellness",
  "Office Supplies",
  "Pet Supplies",
];

export const repairsArr = [
  "In-Home Appliances Repair",
  "Washer Repair",
  "Dryer Repair",
  "Refrigerator Repair",
  "Dishwasher Repair",
  "Oven Repair",
  "Repair Appointment Lookup",
  "Maintain Appliances",
  "Protection Agreements",
];
