export const shopMenuArr = [
  "appliances",
  "tools",
  "boys",
  "girls",
  "men",
  "women",
  "baby",
  "Fitness & Sports",
  "Home & Garden",
  "Mattresses & Accessories",
  "TVs & Electronics",
  // "Toys & Games",
  // "Jewelry & watches",
  // "Seasonal",
  // "Parts & Accessories",
  // "Fan Shop",
  // "Automotive",
  // "Beauty",
  // "Books & Magazines",
  // "Connectes Solutions",
  // "Food & Grocery",
  // "Health & Wellness",
  // "Office Supplies",
  // "Pet Supplies",
];

export const repairsArr = [
  "In-Home Appliances Repair",
  "Washer Repair",
  "Dryer Repair",
  "Refrigerator Repair",
  "Dishwasher Repair",
  "Oven Repair",
  "Repair Appointment Lookup",
  "Maintain Appliances",
  "Protection Agreements",
];
